# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lotu}
  s.version = "0.1.15"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["lobo_tuerto"]
  s.date = %q{2011-02-24}
  s.description = %q{lotu aims to bring an agile and simple game development framework to life. It provides useful abstractions so you can concentrate on developing your game.}
  s.email = %q{dev@lobotuerto.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    ".document",
    ".rspec",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "examples/01_hello_world/moving_portraits.rb",
    "examples/02_screen_cursor/mouse_and_keyboard_cursors.rb",
    "examples/03_collisions/box.rb",
    "examples/04_steering_behaviors/pursuit_and_evade.rb",
    "examples/04_steering_behaviors/pursuit_and_evade_multiple.rb",
    "examples/media/animations/missile.png",
    "examples/media/animations/missile.txt",
    "examples/media/images/cohete-big.png",
    "examples/media/images/cohete-medium.png",
    "examples/media/images/cohete-small.png",
    "examples/media/images/crosshair-1.png",
    "examples/media/images/crosshair-2.png",
    "examples/media/images/crosshair-3.png",
    "examples/media/images/lobo_tuerto.png",
    "examples/media/images/missile-med.png",
    "examples/media/images/silo.png",
    "lib/lotu.rb",
    "lib/lotu/actor.rb",
    "lib/lotu/behavior.rb",
    "lib/lotu/behaviors/collidable.rb",
    "lib/lotu/behaviors/controllable.rb",
    "lib/lotu/behaviors/eventful.rb",
    "lib/lotu/behaviors/resource_manager.rb",
    "lib/lotu/behaviors/system_user.rb",
    "lib/lotu/cursor.rb",
    "lib/lotu/game.rb",
    "lib/lotu/helpers/kernel.rb",
    "lib/lotu/helpers/string.rb",
    "lib/lotu/helpers/vector2d.rb",
    "lib/lotu/systems/animation_system.rb",
    "lib/lotu/systems/base_system.rb",
    "lib/lotu/systems/collision_system.rb",
    "lib/lotu/systems/input_manager_system.rb",
    "lib/lotu/systems/interpolation_system.rb",
    "lib/lotu/systems/stalker_system.rb",
    "lib/lotu/systems/steering_system.rb",
    "lib/lotu/text_box.rb",
    "lotu.gemspec",
    "spec/lotu/actor_spec.rb",
    "spec/lotu/game_spec.rb",
    "spec/lotu/shared_spec.rb",
    "test/actor_test.rb"
  ]
  s.homepage = %q{http://github.com/lobo-tuerto/lotu}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{A simple, agile Ruby game development framework.}
  s.test_files = [
    "examples/01_hello_world/moving_portraits.rb",
    "examples/02_screen_cursor/mouse_and_keyboard_cursors.rb",
    "examples/03_collisions/box.rb",
    "examples/04_steering_behaviors/pursuit_and_evade.rb",
    "examples/04_steering_behaviors/pursuit_and_evade_multiple.rb",
    "spec/lotu/actor_spec.rb",
    "spec/lotu/game_spec.rb",
    "spec/lotu/shared_spec.rb",
    "test/actor_test.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<gosu>, [">= 0.7.27.1"])
      s.add_development_dependency(%q<rspec>, [">= 2.5.0"])
    else
      s.add_dependency(%q<gosu>, [">= 0.7.27.1"])
      s.add_dependency(%q<rspec>, [">= 2.5.0"])
    end
  else
    s.add_dependency(%q<gosu>, [">= 0.7.27.1"])
    s.add_dependency(%q<rspec>, [">= 2.5.0"])
  end
end

