# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lotu}
  s.version = "0.1.13"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["lobo_tuerto"]
  s.date = %q{2010-03-31}
  s.description = %q{lotu aims to bring an agile and simple game development framework to life. It provides useful abstractions so you can concentrate on developing your game.}
  s.email = %q{dev@lobotuerto.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/hello_world/moving_portraits.rb",
     "examples/media/animations/missile.png",
     "examples/media/animations/missile.txt",
     "examples/media/images/cohete-big.png",
     "examples/media/images/cohete-medium.png",
     "examples/media/images/cohete-small.png",
     "examples/media/images/crosshair-1.png",
     "examples/media/images/crosshair-2.png",
     "examples/media/images/crosshair-3.png",
     "examples/media/images/lobo_tuerto.png",
     "examples/media/images/missile-med.png",
     "examples/media/images/silo.png",
     "examples/screen_cursor/mouse_and_keyboard_cursors.rb",
     "examples/steering_behaviors/pursuit_and_evade.rb",
     "examples/steering_behaviors/pursuit_and_evade_multiple.rb",
     "lib/lotu.rb",
     "lib/lotu/actor.rb",
     "lib/lotu/behaviors/collidable.rb",
     "lib/lotu/behaviors/controllable.rb",
     "lib/lotu/behaviors/eventful.rb",
     "lib/lotu/behaviors/system_user.rb",
     "lib/lotu/cursor.rb",
     "lib/lotu/game.rb",
     "lib/lotu/misc/string.rb",
     "lib/lotu/misc/vector2d.rb",
     "lib/lotu/system.rb",
     "lib/lotu/systems/animation_system.rb",
     "lib/lotu/systems/collision_system.rb",
     "lib/lotu/systems/fps_system.rb",
     "lib/lotu/systems/input_system.rb",
     "lib/lotu/systems/stalker_system.rb",
     "lib/lotu/systems/steering_system.rb",
     "lib/lotu/systems/transformation_system.rb",
     "lib/lotu/text_box.rb",
     "lotu.gemspec",
     "test/actor_test.rb"
  ]
  s.homepage = %q{http://github.com/lobo-tuerto/lotu}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A simple, agile Ruby game development framework.}
  s.test_files = [
    "test/actor_test.rb",
     "examples/steering_behaviors/pursuit_and_evade.rb",
     "examples/steering_behaviors/pursuit_and_evade_multiple.rb",
     "examples/hello_world/moving_portraits.rb",
     "examples/screen_cursor/mouse_and_keyboard_cursors.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<gosu>, [">= 0.7.18"])
    else
      s.add_dependency(%q<gosu>, [">= 0.7.18"])
    end
  else
    s.add_dependency(%q<gosu>, [">= 0.7.18"])
  end
end

